export default {
	name: 'siteSettings',
	title: 'Site Settings',
	type: 'document',
	__experimental_actions: ['update', 'publish'],
	fields: [
		{ name: 'siteName', title: 'Site Name', type: 'string' },
		{
			name: 'siteUrl',
			title: 'Website URL',
			type: 'url',
			description: 'e.g., "https://spiritmediapublishing.com"',
		},
		{ name: 'tagline', title: 'Tagline', type: 'string' },
		{ name: 'description', title: 'Site Description', type: 'text' },
		{
			name: 'email',
			title: 'General Contact Email',
			type: 'string',
			description: 'Main contact email for inquiries',
		},
		{
			name: 'primaryEmail',
			title: 'Primary Email (for forms)',
			type: 'string',
			description: 'Primary email address (typically info@...)',
		},
		{
			name: 'submissionsEmail',
			title: 'Submissions Email',
			type: 'string',
			description: 'Email for manuscript submissions and publisher inquiries',
		},
		{
			name: 'kevinEmail',
			title: 'Kevin Direct Email',
			type: 'string',
			description: 'Direct email for Kevin (editor/publisher contact)',
		},
		{ name: 'phone', title: 'Phone', type: 'string' },
		{ name: 'address', title: 'Physical Address', type: 'text' },
		{
			name: 'logo',
			title: 'Logo',
			type: 'image',
			options: { hotspot: true },
		},
		{
			name: 'logoAlt',
			title: 'Logo Alt Text',
			type: 'string',
			description: 'Accessibility text for logo (e.g., "Spirit Media Publishing logo")',
		},
		{
			name: 'heroImage',
			title: 'Default Hero Image',
			type: 'image',
			options: { hotspot: true },
		},
		{
			name: 'heroImageAlt',
			title: 'Hero Image Alt Text',
			type: 'string',
			description: 'Descriptive text for default hero image',
		},
		{
			name: 'homepageHeroImage',
			title: 'Homepage Hero Image (book collage)',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image on homepage',
		},
		{
			name: 'homepageHeroImageAlt',
			title: 'Homepage Hero Image Alt Text',
			type: 'string',
		},
		{
			name: 'publishingHeroImage',
			title: 'Publishing Page Hero Image',
			type: 'image',
			options: { hotspot: true },
		},
		{
			name: 'publishingHeroImageAlt',
			title: 'Publishing Hero Image Alt Text',
			type: 'string',
		},
		{
			name: 'marketingHeroImage',
			title: 'Marketing Page Hero Image',
			type: 'image',
			options: { hotspot: true },
		},
		{
			name: 'marketingHeroImageAlt',
			title: 'Marketing Hero Image Alt Text',
			type: 'string',
		},
		{
			name: 'aboutHeroImage',
			title: 'About Page Hero Image (book collage)',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image on about page',
		},
		{
			name: 'aboutHeroImageAlt',
			title: 'About Hero Image Alt Text',
			type: 'string',
		},
		{
			name: 'contactPageHeroImage',
			title: 'Contact Page Hero Image (books)',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image on contact page',
		},
		{
			name: 'contactPageHeroImageAlt',
			title: 'Contact Page Hero Image Alt Text',
			type: 'string',
		},
		{
			name: 'aboutKevinShellyImage',
			title: 'About Page - Kevin & Shelly Photo',
			type: 'image',
			options: { hotspot: true },
			description: 'Leadership photo section on about page',
		},
		{
			name: 'aboutKevinShellyImageAlt',
			title: 'Kevin & Shelly Photo Alt Text',
			type: 'string',
		},
		{
			name: 'publishingFreeGuideImage',
			title: 'Publishing Page - Free Guide Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Book cover image for Ultimate Book Marketing Guide section',
		},
		{
			name: 'publishingFreeGuideImageAlt',
			title: 'Publishing Free Guide Image Alt Text',
			type: 'string',
		},
		{
			name: 'ogImage',
			title: 'OG Image (for social sharing)',
			type: 'image',
			options: { hotspot: true },
		},
		{
			name: 'ogImageAlt',
			title: 'OG Image Alt Text',
			type: 'string',
			description: 'Alt text for OG image',
		},
		{ name: 'facebook', title: 'Facebook URL', type: 'url' },
		{ name: 'instagram', title: 'Instagram URL', type: 'url' },
		{ name: 'youtube', title: 'YouTube URL', type: 'url' },
		{ name: 'linkedin', title: 'LinkedIn URL', type: 'url' },
		{ name: 'twitter', title: 'Twitter/X URL', type: 'url' },
		{
			name: 'twitterHandle',
			title: 'Twitter Handle (for meta tags, e.g., @spiritmediaus)',
			type: 'string',
		},
		{ name: 'googleAnalyticsId', title: 'Google Analytics ID (GA4)', type: 'string' },
		{
			name: 'homepageAudioUrl',
			title: 'Homepage - Audio Message URL',
			type: 'url',
			description: 'Audio file URL for the prayer message on homepage',
		},
		{
			name: 'kmcHeroImage',
			title: 'Kingdom Messenger Collective Hero Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image on KMC program page',
		},
		{
			name: 'kmcHeroImageAlt',
			title: 'KMC Hero Image Alt Text',
			type: 'string',
		},
		// Brand/Program Images (for homepage brand cards section)
		{
			name: 'fhbImage',
			title: 'Father\'s Heart Bible Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for FHB card on homepage',
		},
		{
			name: 'fhbImageAlt',
			title: 'FHB Image Alt Text',
			type: 'string',
		},
		{
			name: 'kmcBrandImage',
			title: 'Kingdom Messenger Collective Brand Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for KMC card on homepage',
		},
		{
			name: 'kmcBrandImageAlt',
			title: 'KMC Brand Image Alt Text',
			type: 'string',
		},
		{
			name: 'woyImage',
			title: 'Work On Yourself Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for WOY card on homepage',
		},
		{
			name: 'woyImageAlt',
			title: 'WOY Image Alt Text',
			type: 'string',
		},
		{
			name: 'expressBooksImage',
			title: 'EXPRESS BOOKS Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for EXPRESS BOOKS card on homepage',
		},
		{
			name: 'expressBooksImageAlt',
			title: 'EXPRESS BOOKS Image Alt Text',
			type: 'string',
		},
		{
			name: 'believerLibraryImage',
			title: 'The Believer\'s Library Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for Believer\'s Library card on homepage',
		},
		{
			name: 'believerLibraryImageAlt',
			title: 'Believer\'s Library Image Alt Text',
			type: 'string',
		},
		// Homepage Service/Process Images
		{
			name: 'homepageManuscriptReviewImage',
			title: 'Homepage - Free Manuscript Review Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for manuscript review section',
		},
		{
			name: 'homepageManuscriptReviewImageAlt',
			title: 'Manuscript Review Image Alt Text',
			type: 'string',
		},
		{
			name: 'homepageChildrensBooksImage',
			title: 'Homepage - Children\'s Books Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for children\'s book covers section',
		},
		{
			name: 'homepageChildrensBooksImageAlt',
			title: 'Children\'s Books Image Alt Text',
			type: 'string',
		},
		{
			name: 'homepageWriteBookImage',
			title: 'Homepage - Help Me Write My Book Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for "Help Me Write My Book" service card',
		},
		{
			name: 'homepageWriteBookImageAlt',
			title: 'Write Book Image Alt Text',
			type: 'string',
		},
		{
			name: 'homepagePublishBookImage',
			title: 'Homepage - Publish My Book Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for "Publish My Book" service card',
		},
		{
			name: 'homepagePublishBookImageAlt',
			title: 'Publish Book Image Alt Text',
			type: 'string',
		},
		{
			name: 'homepageMarketMessageImage',
			title: 'Homepage - Market My Message Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Featured image for "Market My Message" service card',
		},
		{
			name: 'homepageMarketMessageImageAlt',
			title: 'Market Message Image Alt Text',
			type: 'string',
		},
	],
};
